### PR TITLE
Release 1.28.0

### PR DESCRIPTION
**Pull request by paolodamico**
Releases PostHog v1.28.0

### CODE REVIEW

**Review by fuziontech — APPROVED** [review]
👨‍🍳 beautiful

**Comment by paolodamico** [comment]
Oops wanted to wait until we have the Array post shipped but no problem, the image is fully ready. I'll publish the Array tomorrow and update the GH tags so everyone is notified of the release.

**Comment by fuziontech** [comment]
oops! well if there are any last minute 🍒 to pick we can always bump to 1.28.1 and really wow people with how fast we iterate :P

**Comment by paolodamico** [comment]
Hahaha yeah, though no worries the image is ready and users can update already

**Pull request merged**
