### PR TITLE
Move charts/posthog postgress helm chart to charts/posthog-postgres

### PR DESCRIPTION
**Pull request by tiina303**
We'll be adding `charts/posthog-clickhouse` to avoid confusion moving postgres version to `charts/posthog-postgres`.

Looked for references to `charts/posthog` in this repo & only the readme matched:
```
> grep "charts/posthog" -r .
./README.md:* [PostHog postgres](https://github.com/PostHog/charts/blob/master/charts/posthog-postgres/README.md)
```

Follow-up I assume I need to make a corresponding update to https://posthog.com/docs/deployment/deploy-kubernetes for that to be 
```
helm repo add posthog-postgres https://posthog.github.io/charts/
helm repo update
helm install posthog-postgres posthog/posthog
```

### CODE REVIEW

**Review by fuziontech — APPROVED** [review]
image

**Comment by macobo** [comment]
Not a fan of putting all of this in the same repo, would rather rename this repo to charts-postgres or smth.

If we do want to keep the naming, then:
- README.md needs to make sense
- https://github.com/PostHog/charts/blob/master/.github/workflows/release.yml needs updating

**Review by macobo — CHANGES_REQUESTED** [review]
Not a fan of putting all of this in the same repo. It's just gonna cause confusion since the workflows for both are separate. I would rather rename this repo to charts-postgres or similar. That said not a blocker.

If we do want to keep everything in one repo, then:

-README.md needs changes
-https://github.com/PostHog/charts/blob/master/.github/workflows/release.yml needs updating

I also recommend thinking through how we'll be hosting the helm chart/under what name to avoid confusion for our users.

**Comment by fuziontech** [comment]
When you say workflows are you talking about GitHub actions? Ideally we'd just no longer support Postgres actions any longer. What do you think about naming the Postgres chart `PostHog_Legacy` or something? We could do development on a branch and nuke the Postgres chart at some point.

Semantically this repo is named `Charts` which implies multiple charts. Maybe we should start all new work in a `PostHog/Chart` repo?

GitLab has it setup this way https://gitlab.com/gitlab-org/charts/gitlab. Interestingly enough they have groups for repos which would be pretty helpful here.

Eventual goal here should be to make this repo only one chart, the ClickHouse backed chart named `PostHog`.

**Comment by tiina303** [comment]
From the perspective of running into the least amount of problems in the future I like the idea of renaming this repo more than having two separate charts here because longer term we will anyway have just one chart here.

**Pull request closed without merging**
